# 05 - Configuration-Driven Pipelines

Nebula pipelines can be defined entirely in configuration (JSON/YAML), enabling:

- **Separation of concerns** - Data engineers define configs, code stays stable
- **Environment flexibility** - Different configs for dev/prod/regions
- **No-code changes** - Adjust pipelines without redeploying

| Part | Topic |
|------|-------|
| **1** | Basic Configuration |
| **2** | Transformer Options |
| **3** | Custom Transformers & Functions |
| **4** | Lazy Parameters (`__ns__`) |
| **5** | Loops (Dynamic Expansion) |
| **6** | Full Examples |

**Pipeline keywords covered in Part 2:**

| Keyword | Type | Description |
|---------|------|-------------|
| `{"store": "key"}` | dict | Save current DF to storage |
| `{"store_debug": "key"}` | dict | Save only when debug mode is on |
| `{"from_store": "key"}` | dict | Replace current DF from storage |
| `"to_lazy"` | string | Convert eager → lazy (Polars) |
| `"collect"` | string | Collect lazy → eager (Polars) |

In [1]:
import polars as pl

from nebula.base import Transformer
from nebula.pipelines.pipeline_loader import load_pipeline
from nebula.storage import nebula_storage as ns

In [2]:
orders = pl.DataFrame({
    "order_id": [1, 2, 3, 4, 5],
    "customer": ["alice", "bob", "alice", "carol", "bob"],
    "amount": [150.0, 75.0, 200.0, 50.0, 300.0],
    "region": ["US", "EU", "US", "APAC", "EU"],
})
orders

shape: (5, 4)
┌──────────┬──────────┬────────┬────────┐
│ order_id ┆ customer ┆ amount ┆ region │
│ ---      ┆ ---      ┆ ---    ┆ ---    │
│ i64      ┆ str      ┆ f64    ┆ str    │
╞══════════╪══════════╪════════╪════════╡
│ 1        ┆ alice    ┆ 150.0  ┆ US     │
│ 2        ┆ bob      ┆ 75.0   ┆ EU     │
│ 3        ┆ alice    ┆ 200.0  ┆ US     │
│ 4        ┆ carol    ┆ 50.0   ┆ APAC   │
│ 5        ┆ bob      ┆ 300.0  ┆ EU     │
└──────────┴──────────┴────────┴────────┘

---
## Part 1: Basic Configuration

The `load_pipeline` function accepts a Python dict (which can come from JSON or YAML files).

### 1.1 Minimal Pipeline

In [3]:
config = {
    "pipeline": [
        {"transformer": "SelectColumns", "params": {"columns": ["order_id", "amount"]}},
        {"transformer": "AssertNotEmpty"},
    ]
}

pipe = load_pipeline(config)
pipe.show(add_params=True)

*** Pipeline *** (2 transformations)
 - SelectColumns -> PARAMS: columns=['order_id', 'amount']
 - AssertNotEmpty

In [4]:
result = pipe.run(orders)
print(result)

2026-02-28 00:25:45,358 | [INFO]: Starting pipeline
2026-02-28 00:25:45,361 | [INFO]: Running 'SelectColumns' ...
2026-02-28 00:25:45,407 | [INFO]: Completed 'SelectColumns' in 0.0s
2026-02-28 00:25:45,412 | [INFO]: Running 'AssertNotEmpty' ...
2026-02-28 00:25:45,415 | [INFO]: Completed 'AssertNotEmpty' in 0.0s
2026-02-28 00:25:45,418 | [INFO]: Pipeline completed in 0.1s

shape: (5, 2)
┌──────────┬────────┐
│ order_id ┆ amount │
│ ---      ┆ ---    │
│ i64      ┆ f64    │
╞══════════╪════════╡
│ 1        ┆ 150.0  │
│ 2        ┆ 75.0   │
│ 3        ┆ 200.0  │
│ 4        ┆ 50.0   │
│ 5        ┆ 300.0  │
└──────────┴────────┘

### 1.2 Loading from Files

In practice, configs come from files:

```python
import json
import yaml  # pip install pyyaml

# From JSON
with open("pipeline.json") as f:
    config = json.load(f)

# From YAML
with open("pipeline.yaml") as f:
    config = yaml.safe_load(f)

pipe = load_pipeline(config)
```

### 1.3 Pipeline-Level Options

In [5]:
config = {
    "name": "Order Processing",
    "df_input_name": "Raw Orders",
    "df_output_name": "Processed Orders",
    "pipeline": [
        {"transformer": "Filter", "params": {
            "input_col": "amount",
            "perform": "keep",
            "operator": "gt",
            "value": 100
        }},
    ]
}

pipe = load_pipeline(config)
pipe.show()

*** Order Processing *** (1 transformation)
 - Filter

---
## Part 2: Transformer Options

Each transformer entry supports these keys:

| Key | Required | Description |
|-----|----------|-------------|
| `transformer` | Yes | Transformer class name |
| `params` | No | Dict of constructor parameters |
| `description` | No | Human-readable description |
| `lazy` | No | If `true`, wrap in LazyWrapper |
| `skip` | No | If `true`, skip this transformer |
| `perform` | No | If `false`, skip this transformer |

In [6]:
config = {
    "pipeline": [
        {
            "transformer": "Filter",
            "description": "Keep only high-value orders",
            "params": {
                "input_col": "amount",
                "perform": "keep",
                "operator": "gt",
                "value": 100
            }
        },
        {
            "transformer": "DropColumns",
            "skip": True,  # This transformer is skipped
            "params": {"columns": "region"}
        },
        {
            "transformer": "SelectColumns",
            "perform": False,  # Same as skip: True
            "params": {"columns": ["order_id"]}
        },
    ]
}

pipe = load_pipeline(config)
pipe.show()

# Only Filter runs - DropColumns and SelectColumns are skipped
result = pipe.run(orders)
print(f"\nColumns: {result.columns}")

2026-02-28 00:25:45,489 | [INFO]: Starting pipeline
2026-02-28 00:25:45,492 | [INFO]: Running 'Filter' ...
2026-02-28 00:25:45,498 | [INFO]: Completed 'Filter' in 0.0s
2026-02-28 00:25:45,501 | [INFO]: Pipeline completed in 0.0s

*** Pipeline *** (1 transformation)
 - Filter
     Description: Keep only high-value orders

Columns: ['order_id', 'customer', 'amount', 'region']

### 2.1 Feature Flags with Skip/Perform

Use environment variables or config flags to conditionally enable transformers:

In [7]:
# Simulate feature flags
ENABLE_EXPENSIVE_VALIDATION = False
ENABLE_DISCOUNT = True

config = {
    "pipeline": [
        {
            "transformer": "AssertCount",
            "description": "Expensive row count validation",
            "perform": ENABLE_EXPENSIVE_VALIDATION,
            "params": {"min_count": 1}
        },
        {
            "transformer": "AddLiterals",
            "description": "Add discount flag",
            "perform": ENABLE_DISCOUNT,
            "params": {
                "data": [{"alias": "has_discount", "value": True}]
            }
        },
    ]
}

pipe = load_pipeline(config)
pipe.show()

*** Pipeline *** (1 transformation)
 - AddLiterals
     Description: Add discount flag

### 2.2 Storage Keywords in Config

In [8]:
ns.clear()

config = {
    "pipeline": [
        {"transformer": "Filter", "params": {
            "input_col": "amount", "perform": "keep", "operator": "gt", "value": 100
        }},
        {"store": "filtered_orders"},
        {"transformer": "SelectColumns", "params": {"columns": ["order_id", "amount"]}},
    ]
}

pipe = load_pipeline(config)
pipe.show()

result = pipe.run(orders)
print(f"\nStored keys: {ns.list_keys()}")

2026-02-28 00:25:45,566 | [INFO]: Nebula Storage: clear.
2026-02-28 00:25:45,568 | [INFO]: Nebula Storage: 0 keys remained after clearing.
2026-02-28 00:25:45,575 | [INFO]: Starting pipeline
2026-02-28 00:25:45,578 | [INFO]: Running 'Filter' ...
2026-02-28 00:25:45,586 | [INFO]: Completed 'Filter' in 0.0s
2026-02-28 00:25:45,589 | [INFO]:    --> Store df with key "filtered_orders"
2026-02-28 00:25:45,592 | [INFO]: Nebula Storage: setting an object (<class 'polars.dataframe.frame.DataFrame'>) with the key "filtered_orders".
2026-02-28 00:25:45,595 | [INFO]: Running 'SelectColumns' ...
2026-02-28 00:25:45,600 | [INFO]: Completed 'SelectColumns' in 0.0s
2026-02-28 00:25:45,603 | [INFO]: Pipeline completed in 0.0s

*** Pipeline *** (2 transformations)
 - Filter
   --> Store df with key "filtered_orders"
 - SelectColumns

Stored keys: ['filtered_orders']

### 2.3 Eagerness Control Keywords

Two string keywords let you switch between Polars eager and lazy execution mid-pipeline.
Both are **Polars-only** — they raise a clear `TypeError` for pandas input.

| Keyword | Input | Output | No-op when… |
|---------|-------|--------|-------------|
| `"to_lazy"` | `pl.DataFrame` / `nw.DataFrame` | `pl.LazyFrame` / `nw.LazyFrame` | frame is already lazy |
| `"collect"` | `pl.LazyFrame` / `nw.LazyFrame` | `pl.DataFrame` / `nw.DataFrame` | frame is already eager |

**Why would you need this in a config-driven pipeline?**

- You receive an eager `DataFrame` but want Polars to optimize the following
  transformations as a single lazy query plan → add `"to_lazy"` first.
- A downstream transformer or export step requires an eager `DataFrame`
  (e.g., writing to Parquet with schema inference) → add `"collect"` before it.
- You need a checkpoint: `"collect"` materializes the result so you can
  inspect or store it, then `"to_lazy"` resumes lazy execution.

In [9]:
# "to_lazy": eager pl.DataFrame → lazy pl.LazyFrame
# orders is a pl.DataFrame — to_lazy defers computation to let
# Polars optimize all following steps as one query plan.

config = {"pipeline": ["to_lazy"]}

pipe = load_pipeline(config)
pipe.show()

result = pipe.run(orders)  # orders is eager
print(f"\nInput type : {type(orders)}")
print(f"Output type: {type(result)}")

2026-02-28 00:25:45,629 | [INFO]: Starting pipeline
2026-02-28 00:25:45,632 | [INFO]: Pipeline completed in 0.0s

*** Pipeline ***
   --> Convert eager DataFrame to lazy frame (Polars only)

Input type : <class 'polars.dataframe.frame.DataFrame'>
Output type: <class 'polars.lazyframe.frame.LazyFrame'>

In [10]:
# "collect": lazy pl.LazyFrame → eager pl.DataFrame
# Materializes the query plan and returns a concrete DataFrame.

orders_lazy = orders.lazy()  # simulate receiving a lazy frame

config = {"pipeline": ["collect"]}

pipe = load_pipeline(config)
pipe.show()

result = pipe.run(orders_lazy)
print(f"\nInput type : {type(orders_lazy)}")
print(f"Output type: {type(result)}")
result

2026-02-28 00:25:45,658 | [INFO]: Starting pipeline
2026-02-28 00:25:45,661 | [INFO]: Pipeline completed in 0.0s

*** Pipeline ***
   --> Collect lazy frame into eager DataFrame (Polars only)

Input type : <class 'polars.lazyframe.frame.LazyFrame'>
Output type: <class 'polars.dataframe.frame.DataFrame'>

shape: (5, 4)
┌──────────┬──────────┬────────┬────────┐
│ order_id ┆ customer ┆ amount ┆ region │
│ ---      ┆ ---      ┆ ---    ┆ ---    │
│ i64      ┆ str      ┆ f64    ┆ str    │
╞══════════╪══════════╪════════╪════════╡
│ 1        ┆ alice    ┆ 150.0  ┆ US     │
│ 2        ┆ bob      ┆ 75.0   ┆ EU     │
│ 3        ┆ alice    ┆ 200.0  ┆ US     │
│ 4        ┆ carol    ┆ 50.0   ┆ APAC   │
│ 5        ┆ bob      ┆ 300.0  ┆ EU     │
└──────────┴──────────┴────────┴────────┘

#### Composing `to_lazy` and `collect` in a real pipeline

A typical pattern: receive an eager `DataFrame`, switch to lazy so Polars can
optimize the filter + select as one pass, then `collect` at the end to hand an
eager result to the next stage.

```yaml
# pipeline.yaml — equivalent YAML
pipeline:
  - to_lazy
  - transformer: Filter
    params: {input_col: amount, perform: keep, operator: gt, value: 100}
  - transformer: SelectColumns
    params: {columns: [order_id, customer, amount]}
  - collect
```

In [11]:
# Realistic use-case: eager input → lazy optimization zone → eager output
# Polars fuses the Filter + SelectColumns into a single optimized query plan.

config = {
    "name": "Lazy-optimized order filter",
    "pipeline": [
        "to_lazy",  # ← switch to lazy: enables Polars query optimization
        {"transformer": "Filter", "params": {
            "input_col": "amount", "perform": "keep", "operator": "gt", "value": 100
        }},
        {"transformer": "SelectColumns", "params": {
            "columns": ["order_id", "customer", "amount"]
        }},
        "collect",  # ← materialize: downstream steps expect an eager DataFrame
    ]
}

pipe = load_pipeline(config)
pipe.show()

result = pipe.run(orders)  # feed an eager DataFrame
print(f"\nInput type : {type(orders)}")
print(f"Output type: {type(result)}")
result

2026-02-28 00:25:45,705 | [INFO]: Starting pipeline 'Lazy-optimized order filter'
2026-02-28 00:25:45,708 | [INFO]: Running 'Filter' ...
2026-02-28 00:25:45,711 | [INFO]: Completed 'Filter' in 0.0s

*** Lazy-optimized order filter *** (2 transformations)
   --> Convert eager DataFrame to lazy frame (Polars only)
 - Filter
 - SelectColumns
   --> Collect lazy frame into eager DataFrame (Polars only)

2026-02-28 00:25:45,713 | [INFO]: Running 'SelectColumns' ...
C:\Users\valer\Desktop\pypr\gitrepos\nebula\venv\lib\site-packages\narwhals\_polars\dataframe.py:152: PerformanceWarning: Determining the column names of a LazyFrame requires resolving its schema, which is a potentially expensive operation. Use `LazyFrame.collect_schema().names()` to get the column names without this warning.
  return self.native.columns
2026-02-28 00:25:45,722 | [INFO]: Completed 'SelectColumns' in 0.0s
2026-02-28 00:25:45,725 | [INFO]: Pipeline 'Lazy-optimized order filter' completed in 0.0s

Input type : <class 'polars.dataframe.frame.DataFrame'>
Output type: <class 'polars.dataframe.frame.DataFrame'>

shape: (3, 3)
┌──────────┬──────────┬────────┐
│ order_id ┆ customer ┆ amount │
│ ---      ┆ ---      ┆ ---    │
│ i64      ┆ str      ┆ f64    │
╞══════════╪══════════╪════════╡
│ 1        ┆ alice    ┆ 150.0  │
│ 3        ┆ alice    ┆ 200.0  │
│ 5        ┆ bob      ┆ 300.0  │
└──────────┴──────────┴────────┘

---
## Part 3: Custom Transformers & Functions

To use transformers not in Nebula's core, pass them via `extra_transformers`. For split/branch functions, use `extra_functions`.

**Best practice:** Use `dict[str, T]` where the **key is the contract** with the config. This is refactor-safe - you can rename Python classes/functions without breaking configs.

### 3.1 Extra Transformers

In [12]:
# Define custom transformers
class AddProcessedFlag(Transformer):
    def _transform_nw(self, df):
        import narwhals as nw
        return df.with_columns(nw.lit(True).alias("processed"))


class DoubleAmount(Transformer):
    def _transform_nw(self, df):
        import narwhals as nw
        return df.with_columns((nw.col("amount") * 2).alias("amount"))


# Config references transformers by name (the dict key)
config = {
    "pipeline": [
        {"transformer": "AddProcessedFlag"},
        {"transformer": "DoubleAmount"},
    ]
}

# Pass custom transformers as dict[str, class]
# Keys are the names used in config - decoupled from Python class names
pipe = load_pipeline(
    config,
    extra_transformers={
        "AddProcessedFlag": AddProcessedFlag,
        "DoubleAmount": DoubleAmount,
    }
)

result = pipe.run(orders.head(2))
print(result)

2026-02-28 00:25:45,772 | [INFO]: Starting pipeline
2026-02-28 00:25:45,774 | [INFO]: Running 'AddProcessedFlag' ...
2026-02-28 00:25:45,778 | [INFO]: Completed 'AddProcessedFlag' in 0.0s
2026-02-28 00:25:45,782 | [INFO]: Running 'DoubleAmount' ...
2026-02-28 00:25:45,787 | [INFO]: Completed 'DoubleAmount' in 0.0s
2026-02-28 00:25:45,790 | [INFO]: Pipeline completed in 0.0s

shape: (2, 5)
┌──────────┬──────────┬────────┬────────┬───────────┐
│ order_id ┆ customer ┆ amount ┆ region ┆ processed │
│ ---      ┆ ---      ┆ ---    ┆ ---    ┆ ---       │
│ i64      ┆ str      ┆ f64    ┆ str    ┆ bool      │
╞══════════╪══════════╪════════╪════════╪═══════════╡
│ 1        ┆ alice    ┆ 300.0  ┆ US     ┆ true      │
│ 2        ┆ bob      ┆ 150.0  ┆ EU     ┆ true      │
└──────────┴──────────┴────────┴────────┴───────────┘

**Why dict keys matter for refactoring:**

```python
# If you rename DoubleAmount → MultiplyAmount in Python:
extra_transformers={
    "DoubleAmount": MultiplyAmount,  # Key stays same, config doesn't break
}
```

### 3.2 Using Modules

For production, organize transformers in modules:

```python
# my_transformers.py
__all__ = ["AddProcessedFlag", "DoubleAmount"]

class AddProcessedFlag(Transformer): ...
class DoubleAmount(Transformer): ...
```

```python
# Load from module
import my_transformers

pipe = load_pipeline(config, extra_transformers=[my_transformers])
```

### 3.3 Extra Functions (for Split/Branch)

In [13]:
def split_by_region(df):
    """Split DataFrame by region."""
    return {
        "us": df.filter(pl.col("region") == "US"),
        "international": df.filter(pl.col("region") != "US"),
    }


config = {
    "split_function": "split_by_region",  # References dict key
    "pipeline": {
        "us": [
            {"transformer": "AddLiterals", "params": {
                "data": [{"alias": "tax_rate", "value": 0.08}]
            }}
        ],
        "international": [
            {"transformer": "AddLiterals", "params": {
                "data": [{"alias": "tax_rate", "value": 0.20}]
            }}
        ],
    }
}

pipe = load_pipeline(
    config,
    extra_functions={
        "split_by_region": split_by_region,  # Key matches config reference
    }
)

pipe.show()
result = pipe.run(orders)
print(result)

2026-02-28 00:25:45,835 | [INFO]: Starting pipeline

*** Pipeline *** (2 transformations)
------ SPLIT ------ (function: split_by_region)
**SPLIT <<< international >>> (1 transformation):
     - AddLiterals
**SPLIT <<< us >>> (1 transformation):
     - AddLiterals
<<< Append DFs >>>

2026-02-28 00:25:45,841 | [INFO]: Entering split
2026-02-28 00:25:45,859 | [INFO]: Running 'AddLiterals' ...
2026-02-28 00:25:45,867 | [INFO]: Completed 'AddLiterals' in 0.0s
2026-02-28 00:25:45,881 | [INFO]: Running 'AddLiterals' ...
2026-02-28 00:25:45,887 | [INFO]: Completed 'AddLiterals' in 0.0s
2026-02-28 00:25:45,912 | [INFO]: Pipeline completed in 0.1s

shape: (5, 5)
┌──────────┬──────────┬────────┬────────┬──────────┐
│ order_id ┆ customer ┆ amount ┆ region ┆ tax_rate │
│ ---      ┆ ---      ┆ ---    ┆ ---    ┆ ---      │
│ i64      ┆ str      ┆ f64    ┆ str    ┆ f64      │
╞══════════╪══════════╪════════╪════════╪══════════╡
│ 2        ┆ bob      ┆ 75.0   ┆ EU     ┆ 0.2      │
│ 4        ┆ carol    ┆ 50.0   ┆ APAC   ┆ 0.2      │
│ 5        ┆ bob      ┆ 300.0  ┆ EU     ┆ 0.2      │
│ 1        ┆ alice    ┆ 150.0  ┆ US     ┆ 0.08     │
│ 3        ┆ alice    ┆ 200.0  ┆ US     ┆ 0.08     │
└──────────┴──────────┴────────┴────────┴──────────┘

### 3.4 Function Dicts (Inline Callables)

Alongside `transformer` entries, you can embed **arbitrary Python functions** directly in a config pipeline using the `function` key:

| Key | Required | Description |
|-----|----------|-------------|
| `function` | Yes | A callable **or** a string name registered in `extra_functions` |
| `args` | No | Positional arguments passed to the function after `df` |
| `kwargs` | No | Keyword arguments passed to the function |
| `description` | No | Human-readable label shown by `pipeline.show()` |
| `skip` | No | If `true`, skip this step |
| `perform` | No | If `false`, skip this step |

This bridges **declarative config** with **imperative logic** — great for one-off transformations that don't warrant a full `Transformer` class.

#### 3.4.1 Direct Callable (Python Dict API)

In [14]:
import polars as pl

# Any regular function that accepts a DataFrame and returns a DataFrame
def tag_source(df):
    """Add a static source tag."""
    return df.with_columns(pl.lit("orders_v2").alias("source"))


config = [
    {"transformer": "SelectColumns", "params": {"columns": ["order_id", "amount"]}},
    # Pass the callable directly – no string lookup needed
    {"function": tag_source, "description": "Tag the data source"},
]

pipe = load_pipeline(config)
pipe.show(add_params=True)

result = pipe.run(orders)
print(result)

2026-02-28 00:25:45,999 | [INFO]: Starting pipeline
2026-02-28 00:25:46,003 | [INFO]: Running 'SelectColumns' ...
2026-02-28 00:25:46,008 | [INFO]: Completed 'SelectColumns' in 0.0s
2026-02-28 00:25:46,011 | [INFO]: Running 'tag_source' ...
2026-02-28 00:25:46,016 | [INFO]: Completed 'tag_source' in 0.0s
2026-02-28 00:25:46,018 | [INFO]: Pipeline completed in 0.0s

*** Pipeline *** (2 transformations)
 - SelectColumns -> PARAMS: columns=['order_id', 'amount']
 - tag_source
     Description: Tag the data source
shape: (5, 3)
┌──────────┬────────┬───────────┐
│ order_id ┆ amount ┆ source    │
│ ---      ┆ ---    ┆ ---       │
│ i64      ┆ f64    ┆ str       │
╞══════════╪════════╪═══════════╡
│ 1        ┆ 150.0  ┆ orders_v2 │
│ 2        ┆ 75.0   ┆ orders_v2 │
│ 3        ┆ 200.0  ┆ orders_v2 │
│ 4        ┆ 50.0   ┆ orders_v2 │
│ 5        ┆ 300.0  ┆ orders_v2 │
└──────────┴────────┴───────────┘

#### 3.4.2 String Name Lookup

In YAML/JSON configs you can't embed callables, so you use a **string name** that is resolved against `extra_functions` at load time — the same registry used for split functions.

```yaml
# pipeline.yaml
pipeline:
  - transformer: SelectColumns
    params: {columns: [order_id, amount]}
  - function: tag_source          # ← resolved from extra_functions
    description: Tag the data source
```

In [15]:
config = [
    {"transformer": "SelectColumns", "params": {"columns": ["order_id", "amount"]}},
    {"function": "tag_source", "description": "Tag the data source"},
]

pipe = load_pipeline(
    config,
    extra_functions={"tag_source": tag_source},  # key = name used in config
)
pipe.show(add_params=True)

result = pipe.run(orders)
print(result)

2026-02-28 00:25:46,055 | [INFO]: Starting pipeline
2026-02-28 00:25:46,058 | [INFO]: Running 'SelectColumns' ...
2026-02-28 00:25:46,062 | [INFO]: Completed 'SelectColumns' in 0.0s
2026-02-28 00:25:46,064 | [INFO]: Running 'tag_source' ...
2026-02-28 00:25:46,068 | [INFO]: Completed 'tag_source' in 0.0s
2026-02-28 00:25:46,072 | [INFO]: Pipeline completed in 0.0s

*** Pipeline *** (2 transformations)
 - SelectColumns -> PARAMS: columns=['order_id', 'amount']
 - tag_source
     Description: Tag the data source
shape: (5, 3)
┌──────────┬────────┬───────────┐
│ order_id ┆ amount ┆ source    │
│ ---      ┆ ---    ┆ ---       │
│ i64      ┆ f64    ┆ str       │
╞══════════╪════════╪═══════════╡
│ 1        ┆ 150.0  ┆ orders_v2 │
│ 2        ┆ 75.0   ┆ orders_v2 │
│ 3        ┆ 200.0  ┆ orders_v2 │
│ 4        ┆ 50.0   ┆ orders_v2 │
│ 5        ┆ 300.0  ┆ orders_v2 │
└──────────┴────────┴───────────┘

#### 3.4.3 Passing Args and Kwargs

In [16]:
def apply_discount(df, col, rate=0.1):
    """Multiply a column by (1 - rate)."""
    return df.with_columns(
        (pl.col(col) * (1 - rate)).alias(col)
    )


def add_batch_tag(df, batch_id, env="prod"):
    """Stamp every row with batch metadata."""
    return df.with_columns(
        pl.lit(batch_id).alias("batch_id"),
        pl.lit(env).alias("env"),
    )


config = [
    # args: positional arguments after df
    {
        "function": "apply_discount",
        "args": ["amount"],          # col = 'amount'
        "kwargs": {"rate": 0.15},     # rate = 0.15
        "description": "Apply 15% discount to amount",
    },
    # kwargs only
    {
        "function": "add_batch_tag",
        "kwargs": {"batch_id": "batch_20260227", "env": "staging"},
        "description": "Stamp batch metadata",
    },
]

pipe = load_pipeline(
    config,
    extra_functions={"apply_discount": apply_discount, "add_batch_tag": add_batch_tag},
)
pipe.show(add_params=True)

result = pipe.run(orders)
print(result)

2026-02-28 00:25:46,121 | [INFO]: Starting pipeline
2026-02-28 00:25:46,125 | [INFO]: Running 'apply_discount' ...
2026-02-28 00:25:46,128 | [INFO]: Completed 'apply_discount' in 0.0s
2026-02-28 00:25:46,131 | [INFO]: Running 'add_batch_tag' ...
2026-02-28 00:25:46,134 | [INFO]: Completed 'add_batch_tag' in 0.0s
2026-02-28 00:25:46,136 | [INFO]: Pipeline completed in 0.0s

*** Pipeline *** (2 transformations)
 - apply_discount -> ARGS=['amount'], KWARGS={'rate': 0.15}
     Description: Apply 15% discount to amount
 - add_batch_tag -> KWARGS={'batch_id': 'batch_20260227', 'env': 'staging'}
     Description: Stamp batch metadata
shape: (5, 6)
┌──────────┬──────────┬────────┬────────┬────────────────┬─────────┐
│ order_id ┆ customer ┆ amount ┆ region ┆ batch_id       ┆ env     │
│ ---      ┆ ---      ┆ ---    ┆ ---    ┆ ---            ┆ ---     │
│ i64      ┆ str      ┆ f64    ┆ str    ┆ str            ┆ str     │
╞══════════╪══════════╪════════╪════════╪════════════════╪═════════╡
│ 1        ┆ alice    ┆ 127.5  ┆ US     ┆ batch_20260227 ┆ staging │
│ 2        ┆ bob      ┆ 63.75  ┆ EU     ┆ batch_20260227 ┆ staging │
│ 3        ┆ alice    ┆ 170.0  ┆ US     ┆ batch_20260227 ┆ staging │
│ 4        ┆ carol    ┆ 42.5   ┆ APAC   ┆ batch_20260227 ┆ staging │
│ 5        ┆ bob      ┆ 255.0  ┆ EU     ┆ batch_20260227 ┆ staging │
└──────────┴──────────┴────────┴────────┴────────────────┴─────────┘

#### 3.4.4 Skip / Perform Flags

Function steps support the same `skip` / `perform` flags as transformers — ideal for feature flags and debug steps.

In [17]:
DEBUG_MODE = False  # flip to True to enable the debug step


def log_shape(df):
    """Debug helper: print shape and return df unchanged."""
    print(f"[DEBUG] shape={df.shape}, columns={df.columns}")
    return df


config = [
    {"transformer": "Filter", "params": {
        "input_col": "amount", "perform": "keep", "operator": "gt", "value": 100
    }},
    # This step only runs when DEBUG_MODE is True
    {
        "function": "log_shape",
        "perform": DEBUG_MODE,
        "description": "Debug: log shape after filter",
    },
    {"transformer": "SelectColumns", "params": {"columns": ["order_id", "customer", "amount"]}},
]

pipe = load_pipeline(config, extra_functions={"log_shape": log_shape})
pipe.show()  # log_shape is absent from the shown pipeline

result = pipe.run(orders)
print(result)

2026-02-28 00:25:46,180 | [INFO]: Starting pipeline

*** Pipeline *** (2 transformations)
 - Filter
 - SelectColumns

2026-02-28 00:25:46,184 | [INFO]: Running 'Filter' ...
2026-02-28 00:25:46,188 | [INFO]: Completed 'Filter' in 0.0s
2026-02-28 00:25:46,191 | [INFO]: Running 'SelectColumns' ...
2026-02-28 00:25:46,194 | [INFO]: Completed 'SelectColumns' in 0.0s
2026-02-28 00:25:46,197 | [INFO]: Pipeline completed in 0.0s

shape: (3, 3)
┌──────────┬──────────┬────────┐
│ order_id ┆ customer ┆ amount │
│ ---      ┆ ---      ┆ ---    │
│ i64      ┆ str      ┆ f64    │
╞══════════╪══════════╪════════╡
│ 1        ┆ alice    ┆ 150.0  │
│ 3        ┆ alice    ┆ 200.0  │
│ 5        ┆ bob      ┆ 300.0  │
└──────────┴──────────┴────────┘

#### 3.4.5 Mixed Pipeline — Transformers + Functions

Functions and transformers compose freely. This is a realistic ETL step where a custom normalisation function lives alongside standard Nebula transformers:

In [18]:
def normalize_amounts(df, decimals=2):
    """Round amounts and cap at a maximum value."""
    return df.with_columns(
        pl.col("amount").round(decimals).clip(upper_bound=250.0).alias("amount")
    )


def add_audit_cols(df, run_id):
    """Append audit columns required by the data warehouse."""
    import datetime
    return df.with_columns(
        pl.lit(run_id).alias("run_id"),
        pl.lit(str(datetime.date.today())).alias("load_date"),
    )


config = {
    "name": "Order ETL",
    "pipeline": [
        # 1. Validate input
        {"transformer": "AssertNotEmpty"},
        # 2. Keep relevant columns
        {"transformer": "SelectColumns",
         "params": {"columns": ["order_id", "customer", "amount", "region"]}},
        # 3. Custom normalisation logic (function, no full Transformer needed)
        {"function": "normalize_amounts",
         "kwargs": {"decimals": 2},
         "description": "Round & cap amounts"},
        # 4. Snapshot intermediate state
        {"store": "normalized_orders"},
        # 5. Standard transformer again
        {"transformer": "Filter",
         "params": {"input_col": "region", "perform": "keep",
                    "operator": "eq", "value": "US"}},
        # 6. Stamp audit columns before writing
        {"function": "add_audit_cols",
         "kwargs": {"run_id": "run_20260227_001"},
         "description": "Append audit metadata"},
    ]
}

pipe = load_pipeline(
    config,
    extra_functions={
        "normalize_amounts": normalize_amounts,
        "add_audit_cols": add_audit_cols,
    }
)
pipe.show(add_params=True)

result = pipe.run(orders)
print(result)
print(f"\nStored 'normalized_orders': {ns.get('normalized_orders').shape}")

2026-02-28 00:25:46,232 | [INFO]: Starting pipeline 'Order ETL'
2026-02-28 00:25:46,235 | [INFO]: Running 'AssertNotEmpty' ...
2026-02-28 00:25:46,237 | [INFO]: Completed 'AssertNotEmpty' in 0.0s
2026-02-28 00:25:46,239 | [INFO]: Running 'SelectColumns' ...

*** Order ETL *** (5 transformations)
 - AssertNotEmpty
 - SelectColumns -> PARAMS: columns=['order_id', 'customer', 'amount', 'region']
 - normalize_amounts -> KWARGS={'decimals': 2}
     Description: Round & cap amounts
   --> Store df with key "normalized_orders"
 - Filter -> PARAMS: input_col="region", operator="eq", perform="keep", value="US"
 - add_audit_cols -> KWARGS={'run_id': 'run_20260227_001'}
     Description: Append audit metadata

2026-02-28 00:25:46,244 | [INFO]: Completed 'SelectColumns' in 0.0s
2026-02-28 00:25:46,249 | [INFO]: Running 'normalize_amounts' ...
2026-02-28 00:25:46,257 | [INFO]: Completed 'normalize_amounts' in 0.0s
2026-02-28 00:25:46,259 | [INFO]:    --> Store df with key "normalized_orders"
2026-02-28 00:25:46,263 | [INFO]: Nebula Storage: setting an object (<class 'polars.dataframe.frame.DataFrame'>) with the key "normalized_orders".
2026-02-28 00:25:46,265 | [INFO]: Running 'Filter' ...
2026-02-28 00:25:46,271 | [INFO]: Completed 'Filter' in 0.0s
2026-02-28 00:25:46,273 | [INFO]: Running 'add_audit_cols' ...
2026-02-28 00:25:46,279 | [INFO]: Completed 'add_audit_cols' in 0.0s
2026-02-28 00:25:46,282 | [INFO]: Pipeline 'Order ETL' completed in 0.0s

shape: (2, 6)
┌──────────┬──────────┬────────┬────────┬──────────────────┬────────────┐
│ order_id ┆ customer ┆ amount ┆ region ┆ run_id           ┆ load_date  │
│ ---      ┆ ---      ┆ ---    ┆ ---    ┆ ---              ┆ ---        │
│ i64      ┆ str      ┆ f64    ┆ str    ┆ str              ┆ str        │
╞══════════╪══════════╪════════╪════════╪══════════════════╪════════════╡
│ 1        ┆ alice    ┆ 150.0  ┆ US     ┆ run_20260227_001 ┆ 2026-02-28 │
│ 3        ┆ alice    ┆ 200.0  ┆ US     ┆ run_20260227_001 ┆ 2026-02-28 │
└──────────┴──────────┴────────┴────────┴──────────────────┴────────────┘

Stored 'normalized_orders': (5, 4)

---
## Part 4: Lazy Parameters (`__ns__`)

For runtime parameter resolution, use `lazy: true` with the `__ns__` prefix to reference values from nebula storage.

See notebook 04 for `LazyWrapper` details.

In [19]:
ns.clear()
ns.set("computed_label", "premium_customer")

config = {
    "pipeline": [
        {
            "transformer": "AddLiterals",
            "lazy": True,  # Enable lazy resolution
            "params": {
                "data": [
                    {"alias": "static_col", "value": "hardcoded"},
                    {"alias": "dynamic_col", "value": "__ns__computed_label"},  # Resolved at runtime
                ]
            }
        }
    ]
}

pipe = load_pipeline(config)
result = pipe.run(orders.head(2))
print(result)

2026-02-28 00:25:46,324 | [INFO]: Nebula Storage: clear.
2026-02-28 00:25:46,327 | [INFO]: Nebula Storage: 0 keys remained after clearing.
2026-02-28 00:25:46,331 | [INFO]: Nebula Storage: setting an object (<class 'str'>) with the key "computed_label".
2026-02-28 00:25:46,335 | [INFO]: Starting pipeline
2026-02-28 00:25:46,340 | [INFO]: Running '(Lazy) AddLiterals' ...
2026-02-28 00:25:46,346 | [INFO]: Completed '(Lazy) AddLiterals' in 0.0s
2026-02-28 00:25:46,349 | [INFO]: Pipeline completed in 0.0s

shape: (2, 6)
┌──────────┬──────────┬────────┬────────┬────────────┬──────────────────┐
│ order_id ┆ customer ┆ amount ┆ region ┆ static_col ┆ dynamic_col      │
│ ---      ┆ ---      ┆ ---    ┆ ---    ┆ ---        ┆ ---              │
│ i64      ┆ str      ┆ f64    ┆ str    ┆ str        ┆ str              │
╞══════════╪══════════╪════════╪════════╪════════════╪══════════════════╡
│ 1        ┆ alice    ┆ 150.0  ┆ US     ┆ hardcoded  ┆ premium_customer │
│ 2        ┆ bob      ┆ 75.0   ┆ EU     ┆ hardcoded  ┆ premium_customer │
└──────────┴──────────┴────────┴────────┴────────────┴──────────────────┘

The `__ns__` prefix works at any nesting depth within `params`.

---
## Part 5: Loops (Dynamic Expansion)

Loops let you generate repetitive pipeline sections dynamically. The `loop` block expands at load time, creating multiple transformers or pipelines from a template.

### 5.1 Basic Loop

In [20]:
config = {
    "pipeline": [
        {
            "loop": {
                "values": {
                    "col_name": ["flag_a", "flag_b", "flag_c"]
                },
                "transformer": "AddLiterals",
                "params": {
                    "data": [{"alias": "<<col_name>>", "value": True}]
                }
            }
        }
    ]
}

pipe = load_pipeline(config)
pipe.show(add_params=True)

*** Pipeline *** (3 transformations)
 - AddLiterals -> PARAMS: data=[{'alias': 'flag_a', 'value': True}]
 - AddLiterals -> PARAMS: data=[{'alias': 'flag_b', 'value': True}]
 - AddLiterals -> PARAMS: data=[{'alias': 'flag_c', 'value': True}]

In [21]:
result = pipe.run(orders.head(2))
print(result)

2026-02-28 00:25:46,411 | [INFO]: Starting pipeline
2026-02-28 00:25:46,413 | [INFO]: Running 'AddLiterals' ...
2026-02-28 00:25:46,417 | [INFO]: Completed 'AddLiterals' in 0.0s
2026-02-28 00:25:46,418 | [INFO]: Running 'AddLiterals' ...
2026-02-28 00:25:46,421 | [INFO]: Completed 'AddLiterals' in 0.0s
2026-02-28 00:25:46,423 | [INFO]: Running 'AddLiterals' ...
2026-02-28 00:25:46,427 | [INFO]: Completed 'AddLiterals' in 0.0s
2026-02-28 00:25:46,430 | [INFO]: Pipeline completed in 0.0s

shape: (2, 7)
┌──────────┬──────────┬────────┬────────┬────────┬────────┬────────┐
│ order_id ┆ customer ┆ amount ┆ region ┆ flag_a ┆ flag_b ┆ flag_c │
│ ---      ┆ ---      ┆ ---    ┆ ---    ┆ ---    ┆ ---    ┆ ---    │
│ i64      ┆ str      ┆ f64    ┆ str    ┆ bool   ┆ bool   ┆ bool   │
╞══════════╪══════════╪════════╪════════╪════════╪════════╪════════╡
│ 1        ┆ alice    ┆ 150.0  ┆ US     ┆ true   ┆ true   ┆ true   │
│ 2        ┆ bob      ┆ 75.0   ┆ EU     ┆ true   ┆ true   ┆ true   │
└──────────┴──────────┴────────┴────────┴────────┴────────┴────────┘

### 5.2 Loop Modes: Linear vs Product

| Mode | Description |
|------|-------------|
| `linear` | Zip values together (default) |
| `product` | Cartesian product of all values |

In [22]:
# Linear mode: zip(["a", "b"], [1, 2]) → [("a", 1), ("b", 2)]
config = {
    "pipeline": [
        {
            "loop": {
                "mode": "linear",
                "values": {
                    "name": ["col_x", "col_y"],
                    "val": [100, 200]
                },
                "transformer": "AddLiterals",
                "params": {
                    "data": [{"alias": "<<name>>", "value": "<<val>>"}]
                }
            }
        }
    ]
}

pipe = load_pipeline(config)
pipe.show(add_params=True)
# Creates: AddLiterals(col_x=100), AddLiterals(col_y=200)

*** Pipeline *** (2 transformations)
 - AddLiterals -> PARAMS: data=[{'alias': 'col_x', 'value': 100}]
 - AddLiterals -> PARAMS: data=[{'alias': 'col_y', 'value': 200}]

In [23]:
# Product mode: product(["a", "b"], [1, 2]) → [("a", 1), ("a", 2), ("b", 1), ("b", 2)]
config = {
    "pipeline": [
        {
            "loop": {
                "mode": "product",
                "values": {
                    "prefix": ["US", "EU"],
                    "metric": ["sales", "returns"]
                },
                "transformer": "AddLiterals",
                "params": {
                    "data": [{"alias": "<<prefix>>_<<metric>>", "value": 0}]
                }
            }
        }
    ]
}

pipe = load_pipeline(config)
pipe.show(add_params=True)
# Creates 4 transformers: US_sales, US_returns, EU_sales, EU_returns

*** Pipeline *** (4 transformations)
 - AddLiterals -> PARAMS: data=[{'alias': 'US_sales', 'value': 0}]
 - AddLiterals -> PARAMS: data=[{'alias': 'US_returns', 'value': 0}]
 - AddLiterals -> PARAMS: data=[{'alias': 'EU_sales', 'value': 0}]
 - AddLiterals -> PARAMS: data=[{'alias': 'EU_returns', 'value': 0}]

### 5.3 Loop Over Pipelines

Loops can generate entire pipelines (with branches):

In [24]:
ns.clear()

config = {
    "pipeline": [
        {"store": "original"},  # Store for branch to read
        {
            "loop": {
                "mode": "linear",
                "values": {
                    "col_name": ["metric_a", "metric_b"],
                    "col_value": [10, 20]
                },
                "branch": {
                    "storage": "original",
                    "end": "join",
                    "on": "order_id",
                    "how": "left"
                },
                "pipeline": [
                    {"transformer": "SelectColumns", "params": {"columns": ["order_id"]}},
                    {"transformer": "AddLiterals", "params": {
                        "data": [{"alias": "<<col_name>>", "value": "<<col_value>>"}]
                    }}
                ]
            }
        }
    ]
}

pipe = load_pipeline(config)
pipe.show(add_params=True)

2026-02-28 00:25:46,522 | [INFO]: Nebula Storage: clear.
2026-02-28 00:25:46,525 | [INFO]: Nebula Storage: 0 keys remained after clearing.

*** Pipeline *** (4 transformations)
   --> Store df with key "original"
*** Pipeline *** (2 transformations)
------ BRANCH (from storage: original) ------
>> Branch (2 transformations):
     - SelectColumns -> PARAMS: columns=['order_id']
     - AddLiterals -> PARAMS: data=[{'alias': 'metric_a', 'value': 10}]
<<< Join DFs >>>
  - how: left
  - on: order_id
*** Pipeline *** (2 transformations)
------ BRANCH (from storage: original) ------
>> Branch (2 transformations):
     - SelectColumns -> PARAMS: columns=['order_id']
     - AddLiterals -> PARAMS: data=[{'alias': 'metric_b', 'value': 20}]
<<< Join DFs >>>
  - how: left
  - on: order_id

In [25]:
result = pipe.run(orders.head(3))
print(result)

2026-02-28 00:25:46,551 | [INFO]: Starting pipeline
2026-02-28 00:25:46,553 | [INFO]:    --> Store df with key "original"
2026-02-28 00:25:46,556 | [INFO]: Nebula Storage: setting an object (<class 'polars.dataframe.frame.DataFrame'>) with the key "original".
2026-02-28 00:25:46,558 | [INFO]: Entering branch
2026-02-28 00:25:46,561 | [INFO]: Running 'SelectColumns' ...
2026-02-28 00:25:46,564 | [INFO]: Completed 'SelectColumns' in 0.0s
2026-02-28 00:25:46,566 | [INFO]: Running 'AddLiterals' ...
2026-02-28 00:25:46,571 | [INFO]: Completed 'AddLiterals' in 0.0s
2026-02-28 00:25:46,579 | [INFO]: Entering branch
2026-02-28 00:25:46,581 | [INFO]: Running 'SelectColumns' ...
2026-02-28 00:25:46,585 | [INFO]: Completed 'SelectColumns' in 0.0s
2026-02-28 00:25:46,587 | [INFO]: Running 'AddLiterals' ...
2026-02-28 00:25:46,589 | [INFO]: Completed 'AddLiterals' in 0.0s
2026-02-28 00:25:46,594 | [INFO]: Pipeline completed in 0.0s

shape: (3, 6)
┌──────────┬──────────┬────────┬────────┬──────────┬──────────┐
│ order_id ┆ customer ┆ amount ┆ region ┆ metric_a ┆ metric_b │
│ ---      ┆ ---      ┆ ---    ┆ ---    ┆ ---      ┆ ---      │
│ i64      ┆ str      ┆ f64    ┆ str    ┆ i32      ┆ i32      │
╞══════════╪══════════╪════════╪════════╪══════════╪══════════╡
│ 1        ┆ alice    ┆ 150.0  ┆ US     ┆ 10       ┆ 20       │
│ 2        ┆ bob      ┆ 75.0   ┆ EU     ┆ 10       ┆ 20       │
│ 3        ┆ alice    ┆ 200.0  ┆ US     ┆ 10       ┆ 20       │
└──────────┴──────────┴────────┴────────┴──────────┴──────────┘

### 5.4 Skip/Perform with Loops

In [26]:
config = {
    "pipeline": [
        {
            "skip": True,  # Entire loop is skipped
            "loop": {
                "values": {"x": [1, 2, 3]},
                "transformer": "AssertNotEmpty"  # Never runs
            }
        },
        {"transformer": "SelectColumns", "params": {"glob": "*"}}
    ]
}

pipe = load_pipeline(config)
pipe.show()  # Only SelectColumns appears

*** Pipeline *** (1 transformation)
 - SelectColumns

---
## Part 6: Complete Examples

### 6.1 Split Pipeline in Config

In [27]:
def split_by_value(df):
    return {
        "high": df.filter(pl.col("amount") >= 150),
        "low": df.filter(pl.col("amount") < 150),
    }


config = {
    "name": "Value-Based Processing",
    "split_function": "split_by_value",
    "split_order": ["high", "low"],
    "pipeline": {
        "high": [
            {"transformer": "AddLiterals", "params": {
                "data": [{"alias": "priority", "value": "high"}]
            }}
        ],
        "low": [
            {"transformer": "AddLiterals", "params": {
                "data": [{"alias": "priority", "value": "standard"}]
            }}
        ]
    }
}

pipe = load_pipeline(config, extra_functions={"split_by_value": split_by_value})
pipe.show()

result = pipe.run(orders)
print(result)

2026-02-28 00:25:46,676 | [INFO]: Starting pipeline 'Value-Based Processing'
2026-02-28 00:25:46,680 | [INFO]: Entering split

*** Value-Based Processing *** (2 transformations)
------ SPLIT ------ (function: split_by_value)
**SPLIT <<< high >>> (1 transformation):
     - AddLiterals
**SPLIT <<< low >>> (1 transformation):
     - AddLiterals
<<< Append DFs >>>

2026-02-28 00:25:46,685 | [INFO]: Running 'AddLiterals' ...
2026-02-28 00:25:46,690 | [INFO]: Completed 'AddLiterals' in 0.0s
2026-02-28 00:25:46,694 | [INFO]: Running 'AddLiterals' ...
2026-02-28 00:25:46,699 | [INFO]: Completed 'AddLiterals' in 0.0s
2026-02-28 00:25:46,710 | [INFO]: Pipeline 'Value-Based Processing' completed in 0.0s

shape: (5, 5)
┌──────────┬──────────┬────────┬────────┬──────────┐
│ order_id ┆ customer ┆ amount ┆ region ┆ priority │
│ ---      ┆ ---      ┆ ---    ┆ ---    ┆ ---      │
│ i64      ┆ str      ┆ f64    ┆ str    ┆ str      │
╞══════════╪══════════╪════════╪════════╪══════════╡
│ 1        ┆ alice    ┆ 150.0  ┆ US     ┆ high     │
│ 3        ┆ alice    ┆ 200.0  ┆ US     ┆ high     │
│ 5        ┆ bob      ┆ 300.0  ┆ EU     ┆ high     │
│ 2        ┆ bob      ┆ 75.0   ┆ EU     ┆ standard │
│ 4        ┆ carol    ┆ 50.0   ┆ APAC   ┆ standard │
└──────────┴──────────┴────────┴────────┴──────────┘

### 6.2 Branch Pipeline in Config

In [28]:
ns.clear()

# Pre-store customer tiers
tiers = pl.DataFrame({
    "customer": ["alice", "bob", "carol"],
    "tier": ["gold", "silver", "bronze"]
})
ns.set("customer_tiers", tiers)

config = {
    "name": "Enrich with Customer Tier",
    "branch": {
        "storage": "customer_tiers",
        "end": "join",
        "on": "customer",
        "how": "left"
    },
    "pipeline": [
        {"transformer": "SelectColumns", "params": {"columns": ["customer", "tier"]}}
    ]
}

pipe = load_pipeline(config)
pipe.show()

result = pipe.run(orders)
print(result)

2026-02-28 00:25:46,745 | [INFO]: Nebula Storage: clear.
2026-02-28 00:25:46,749 | [INFO]: Nebula Storage: 0 keys remained after clearing.
2026-02-28 00:25:46,753 | [INFO]: Nebula Storage: setting an object (<class 'polars.dataframe.frame.DataFrame'>) with the key "customer_tiers".
2026-02-28 00:25:46,760 | [INFO]: Starting pipeline 'Enrich with Customer Tier'
2026-02-28 00:25:46,762 | [INFO]: Entering branch
2026-02-28 00:25:46,765 | [INFO]: Running 'SelectColumns' ...
2026-02-28 00:25:46,771 | [INFO]: Completed 'SelectColumns' in 0.0s
2026-02-28 00:25:46,781 | [INFO]: Pipeline 'Enrich with Customer Tier' completed in 0.0s

*** Enrich with Customer Tier *** (1 transformation)
------ BRANCH (from storage: customer_tiers) ------
>> Branch (1 transformation):
     - SelectColumns
<<< Join DFs >>>
shape: (5, 5)
┌──────────┬──────────┬────────┬────────┬────────┐
│ order_id ┆ customer ┆ amount ┆ region ┆ tier   │
│ ---      ┆ ---      ┆ ---    ┆ ---    ┆ ---    │
│ i64      ┆ str      ┆ f64    ┆ str    ┆ str    │
╞══════════╪══════════╪════════╪════════╪════════╡
│ 1        ┆ alice    ┆ 150.0  ┆ US     ┆ gold   │
│ 2        ┆ bob      ┆ 75.0   ┆ EU     ┆ silver │
│ 3        ┆ alice    ┆ 200.0  ┆ US     ┆ gold   │
│ 4        ┆ carol    ┆ 50.0   ┆ APAC   ┆ bronze │
│ 5        ┆ bob      ┆ 300.0  ┆ EU     ┆ silver │
└──────────┴──────────┴────────┴────────┴────────┘

### 6.3 Apply-to-Rows in Config

In [29]:
config = {
    "name": "Discount High-Value Orders",
    "apply_to_rows": {
        "input_col": "amount",
        "operator": "ge",
        "value": 200
    },
    "pipeline": [
        {"transformer": "AddLiterals", "params": {
            "data": [{"alias": "discount", "value": 0.10}]
        }}
    ],
    "otherwise": [
        {"transformer": "AddLiterals", "params": {
            "data": [{"alias": "discount", "value": 0.0}]
        }}
    ]
}

pipe = load_pipeline(config)
pipe.show()

result = pipe.run(orders)
print(result)

2026-02-28 00:25:46,821 | [INFO]: Starting pipeline 'Discount High-Value Orders'

*** Discount High-Value Orders *** (2 transformations)
------ APPLY TO ROWS (amount ge 200) ------
>> Apply To rows (1 transformation):
     - AddLiterals
>> Otherwise (1 transformation)
     - AddLiterals
<<< Append DFs >>>

2026-02-28 00:25:46,825 | [INFO]: Entering apply_to_rows
2026-02-28 00:25:46,844 | [INFO]: Running 'AddLiterals' ...
2026-02-28 00:25:46,851 | [INFO]: Completed 'AddLiterals' in 0.0s
2026-02-28 00:25:46,856 | [INFO]: Running 'AddLiterals' ...
2026-02-28 00:25:46,860 | [INFO]: Completed 'AddLiterals' in 0.0s
2026-02-28 00:25:46,867 | [INFO]: Pipeline 'Discount High-Value Orders' completed in 0.0s

shape: (5, 5)
┌──────────┬──────────┬────────┬────────┬──────────┐
│ order_id ┆ customer ┆ amount ┆ region ┆ discount │
│ ---      ┆ ---      ┆ ---    ┆ ---    ┆ ---      │
│ i64      ┆ str      ┆ f64    ┆ str    ┆ f64      │
╞══════════╪══════════╪════════╪════════╪══════════╡
│ 3        ┆ alice    ┆ 200.0  ┆ US     ┆ 0.1      │
│ 5        ┆ bob      ┆ 300.0  ┆ EU     ┆ 0.1      │
│ 1        ┆ alice    ┆ 150.0  ┆ US     ┆ 0.0      │
│ 2        ┆ bob      ┆ 75.0   ┆ EU     ┆ 0.0      │
│ 4        ┆ carol    ┆ 50.0   ┆ APAC   ┆ 0.0      │
└──────────┴──────────┴────────┴────────┴──────────┘

---
## Summary

| Feature | Syntax |
|---------|--------|
| Basic transformer | `{"transformer": "Name", "params": {...}}` |
| Skip/disable | `"skip": true` or `"perform": false` |
| Description | `"description": "Human-readable text"` |
| Lazy params | `"lazy": true` + `"__ns__key"` in params |
| Storage | `{"store": "key"}`, `{"store_debug": "key"}`, `{"from_store": "key"}` |
| Eagerness | `"to_lazy"` (eager → lazy), `"collect"` (lazy → eager) |
| Loops | `{"loop": {"values": {...}, "transformer": ...}}` |
| Custom transformers | `extra_transformers={"Name": Class}` |
| Custom functions | `extra_functions={"function": func_or_name, "args": [...], "kwargs": {...}}` |

**Best practices:**
- Use `dict[str, T]` for extras (refactor-safe)
- Keep config keys stable, even if Python names change
- Use `skip`/`perform` for feature flags
- Organize custom transformers in modules with `__all__`
- Pair `"to_lazy"` + `"collect"` to bracket a lazy optimization zone

In [30]:
ns.clear()

2026-02-28 00:25:46,900 | [INFO]: Nebula Storage: clear.
2026-02-28 00:25:46,903 | [INFO]: Nebula Storage: 0 keys remained after clearing.